version: 2.1
workflows:
  version: 2
  pre-prod:
   jobs:
      - yaml-lint:
          filters:
            branches:
            ignore: master
      - dev_build:
          filters:
            branches:
              ignore: master
  prod:
   jobs:
      - yaml-lint:
          filters:
            branches:
              only: master
      - build-publish:
          filters:
            branches:
              only: master
jobs:
  yaml-lint:
    docker:
      - image: sdesbure/yamllint

    working_directory: ~/project
    steps:
      - checkout
      - run: yamllint .circleci/.

  dev_build:
    docker:
      - image: circleci/python:2.7

    steps:
      - checkout
      - setup_remote_docker:
          reusable: true    # default - false
          exclusive: true   # default - true
          # Temporary workaround for Circle CI issue
          # https://discuss.circleci.com/t/setup-remote-docker-connection-failures/26434
          version: 18.05.0-ce

      - run:
          name: Docker Build
          command: docker build .

  build-publish:
    docker:
      - image: circleci/python:2.7

    steps:
      - checkout
      - setup_remote_docker:
          reusable: true    # default - false
          exclusive: true   # default - true
          # Temporary workaround for Circle CI issue
          # https://discuss.circleci.com/t/setup-remote-docker-connection-failures/26434
          version: 18.05.0-ce

      - run:
          name: Docker Build and Publish
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t robot297/jenkins-container:$TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push robot297/jenkins-container:$TAG
