version: 2.1
workflows:
  version: 2
  build:
    jobs:
      - yaml-lint
      - build
jobs:
  yaml-lint:
    docker:
      - image: sdesbure/yamllint

    working_directory: ~/project
    steps:
      - checkout
      - run: yamllint .circleci/.

  build:
    except:
      - master
    docker:
      - image: csanchez/kaniko:latest

    steps:
      - checkout

      - run:
          name: Docker Build
          command: executor --context ~/project --verbosity warn --no-push
